### ISSUE TITLE
packages/apps/exTHmSettings/src/com/exthm/settings/fragments/PowerMenuSettings.java

### ISSUE THREAD

**Issue by chiajiaen** [exthmui/android_packages_apps_exTHmSettings#3] opened 2020-01-04 02:38 UTC
packages/apps/exTHmSettings/src/com/exthm/settings/fragments/PowerMenuSettings.java:67: error: cannot find symbol
                Settings.System.POWERMENU_TORCH, 0) == 1));
                               ^
  symbol:   variable POWERMENU_TORCH
  location: class System
packages/apps/exTHmSettings/src/com/exthm/settings/fragments/PowerMenuSettings.java:76: error: cannot find symbol
                    Settings.System.POWERMENU_TORCH, value ? 1 : 0);
                                   ^
  symbol:   variable POWERMENU_TORCH
  location: class System
4 errors

**Comment by atmouse-** [comment] 2020-01-04 10:02
Duplicate of #2

**Closed** 2020-01-04 13:06 UTC
